content/events/2019-03-19-cube-food-week.md

Reviewer: @ubccsss/vp-communications

Fixed link to SAGM

---

content/posts/2019-04-06-year-end-cruise-update.md

Reviewer: @ubccsss/vp-communications

Added gala update post

---

README.md
content/events/2019-09-04-introducing-the-cube.md
content/events/2019-09-09-technical-clubs-days.md
content/events/2019-09-13-studio-ghibli-bbt-night.md
content/events/2019-09-19-free-breakfast.md
content/events/2019-09-25-first-year-panel.md
content/events/2019-11-20-hot-chocolate.md
content/events/2019-11-22-SAGM.md
content/events/2019-11-29-meet-the-profs.md
layouts/partials/event/add-to-calendar.html

Fixes "Add to calendar" by ensuring end dates are after start dates

Fix end date for recent events

---

content/services/courses/cpsc-221.md

added description for cpsc 221

Create cpsc-221.md, class description for CPSC 221

---

content/services/courses/cpsc-302.md

Noticed comments were for 304 not for 302

Removed incorrect course comments

---

content/services/tutor.md

Added CPSC 210 for Kamsi Oramasionwu's courses
Added new tutors for 2021, still need to remove obsolete tutor info

Update tutor information

---

content/services/_index.md
content/services/coffeechat.md

This PR adds 'check back in term two' note to both the [services](https://ubccsss.org/services/) card, and a note to the [Coffee Chats](https://ubccsss.org/services/coffeechat/) page.

Add TBD note to Coffee Chats

---

content/services/tutor.md

Add the tutor disclaimer #100

---

assets/js/create-github-issue.js
content/services/_index.md
content/services/courses/_index.md
layouts/partials/github-issue-form.html
layouts/partials/related-form.html
layouts/services/course.html

- added Js for making a request to [worker](https://github.com/ubccsss/github-issues-worker)
- added a partial containing the form
- updated some text

GitHub issue form

---

content/services/courses/cpsc-311.md
content/services/courses/cpsc-317.md

This PR adds Eric's CPSC 311 and 317 reviews (#134, #133).

Add Eric's 311 and 317 reviews

---

content/contact/suggestions-box.md

Previously, the form was not loading on localhost.
Before:
Now:

Surround iframe with <p> tag

---

assets/js/create-github-issue.js

'use strict' could potentially cause hard-to-find bugs if future maintainers are unaware of it. It also doesn't add much to this code block.

Removed 'use strict' from create-github-issue

---

content/services/_index.md
layouts/shortcodes/card.html

Fixed an issue that caused cards to appear incorrectly on md-sized devices.
Before: 
Now:

Fix card width issue on md-sized devices

---

data/tutor.yaml

I am actually thinking maybe it might be a good idea to randomize tutor display (instead of alphabetical order) since we have quite a number of tutors for certain courses (CPSC110, 210 etc.). 
Also, I was using Prettier, so a lot of auto-formatting happened 😆

Updated tutor information 2021-01-21

---

layouts/shortcodes/tutors.html

This PR adds randomization of tutor display and a sort button to sort tutors alphabetically (#144).
- The randomization applies when 1) the page is first loaded, 2) a course filter is applied, and 3) all course filters are removed / all tutors are shown.
- Sorting works in both directions: ascending alphabetically and descending alphabetically.
Let me know if there are any change needed or any additional options to add for sorting and randomization!

Add tutor randomization + alphabetical sorting

---

assets/js/create-github-issue.js
config/_default/config.yml
config/_default/menu.yml
config/_default/params.yml
config/development/params.yml
config/preview/params.yml
config/production/params.yml
layouts/partials/github-issue-form.html
netlify.toml

- Added reCAPTCHA for GitHub issues form
- Replaced `config.yml` with `./config` folder
- This will make it possible to create environment-specific Hugo site params
- For example, there is a different worker URL for dev and production. Instead of manually keeping track of it, running `hugo server` defaults to the dev environment and it'll automatically select the correct URL.
- Current environments: `development` (local), `production`, `preview` (for Netlify previews)
- Use `hugo server -e <env>` to run a specific environment.
- Removed GoogleAnalytics key (#110) while migrating to the new config structure.
- Set Hugo environment to `preview` for Netlify deployment previews (7c5eb3ec940725710856944c52fb642d4c631c63)
- Other minor changes
Went a little overboard, because I got frustrated …

Recaptcha course review form, and more

---

content/events/2022-01-27-tech-industry-night.md
content/events/2022-03-17-tech-industry-night.md

- Changed Solidigm's profile
- Added a month + year to distinguish different industry nights

More updates to industry night event

---

config/development/params.yml
config/preview/params.yml
config/production/params.yml

Add env variables for Cloudflare Analytics manual setup

---

content/about/team/executives/2019.md
content/about/team/executives/2020.md
content/about/team/executives/2021.md
content/events/2022-03-25-elections.md

Updated voting event

---

README.md

Add note about CF Analytics ENV variable in README

---

content/services/_index.md
data/home_cube.yaml

Quick Fix: Change links

---

content/services/courses/cpsc-221.md
content/services/courses/cpsc-304.md
content/services/courses/cpsc-310.md
content/services/courses/cpsc-311.md
content/services/courses/cpsc-312.md
content/services/courses/cpsc-317.md
content/services/courses/cpsc-319.md
content/services/courses/cpsc-406.md
content/services/courses/cpsc-411.md
content/services/courses/cpsc-415.md
content/services/courses/cpsc-416.md
content/services/courses/cpsc-421.md
content/services/courses/cpsc-425.md

This PR adds course review dates to all the course reviews currently in the database. The dates were pulled directly from the Reddit / PRs / blog posts as appropriate.
For example:

Add course review dates

---

assets/css/styles.css
config/_default/params.yml
content/_index.md
layouts/index.html
layouts/partials/header.html
layouts/partials/search-box.html
layouts/partials/sidebar.html

The goal of this revamp was to add as much important content to the homepage so that it becomes easier for new users to find stuff. 
This is just the first prototype, so the code is a little messy. Let me know if you all think we need to add/change anything visually. After we finalize the design, I will push a commit to clean everything up and add comments.

Revamped home page

---

content/about/team/executives/2022.md

I fixed it yesterday but the image came back, not sure what happened but we'll try again

Remove duplicate image

---

assets/js/create-github-issue.js
themes/hugo-bootstrap-5/layouts/partials/github-issue-form.html

This PR passes the `difficulty` and `overall` course quality options to the worker.
(I also ran auto-format on this, the only significant diff is [here](https://github.com/ubccsss/ubccsss.org/compare/master...kewbish:em-add-difficulty-overall-params?expand=1#diff-05b2be1274aac294fead24df7d2d56212cc5f0cc9c8d6926c3706e8424737ea5R51-R58).)

Add difficulty + overall options to script

---

assets/js/create-github-issue.js
themes/hugo-bootstrap-5/layouts/partials/github-issue-form.html

This PR makes the difficulty and overall course quality parameters required in the course review form (closing #243).

Make difficulty + overall requirements required

---

assets/js/newsletter.js
content/_index.md
layouts/partials/newsletter.html
themes/hugo-bootstrap-5/layouts/_default/baseof.html

Add newsletter prompt and link

---

data/courseReviews/cpsc-330.yaml
themes/hugo-bootstrap-5/layouts/partials/course/review.html

Closes #195 - no author attribution could be found for the username.

Add CPSC330 Review

---

layouts/partials/courses-graph.html
themes/hugo-bootstrap-5/layouts/services/courses.html

Added iframe with course requirements graph

---

content/volunteer/_index.md
layouts/partials/newsletter.html
netlify.toml
themes/hugo-bootstrap-5/layouts/_default/baseof.html

The new google form cannot be embedded because it makes use of "File Upload questions" for the resume upload.

Updated Hugo, Bootstrap, newsletter popup text, google forms iframe link

---

data/courseReviews/cpsc-313.yaml

closes #262 
@kewbish does `Overall: 5/5` refer to quality?
It's kinda confusing.

Created CPSC 313 review

---

assets/js/create-github-issue.js
themes/hugo-bootstrap-5/layouts/partials/github-issue-form.html
themes/hugo-bootstrap-5/layouts/services/course.html

As per [this comment](https://github.com/ubccsss/ubccsss.org/pull/263#issuecomment-1275219026), the `overall` parameter name is confusing. Just renamed it to `quality`.

[Course database] Rename overall → quality

---

README.md

Theme is no longer in a submodule

Remove recursive flag from clone instructions

---

content/about/_index.md

Add newsletter + IG to /about

---

data/courseReviews/cpsc-110.yaml

https://deploy-preview-271--ubccsss.netlify.app/services/courses/cpsc-110/

New 110 review

---

data/courseReviews/cpsc-110.yaml
data/courseReviews/cpsc-121.yaml
data/courseReviews/cpsc-210.yaml
data/courseReviews/cpsc-221.yaml
data/courseReviews/cpsc-320.yaml
data/courseReviews/cpsc-340.yaml

This PR closes:
- #276 
- #277 
- #278 
- #279 
- #280 
- #281 
- #282 
- #283 
- #284 
- #285 
- #286 
- #287 
- #288 
- #289 
- #290

Add batch of new course reviews

---

data/courseReviews/cpsc-310.yaml

Add new 310 review

---

themes/hugo-bootstrap-5/layouts/services/course.html

Bold course description

---

content/about/minutes/_index.md
themes/hugo-bootstrap-5/layouts/services/course.html

Added 2022-2023 meeting minutes and fixed a typo.

Added 2022-2023 meeting minutes

---

config/_default/menu.yml
content/about/_index.md

Clean up header

---

content/tcf/animal-logic.md
content/tcf/arista-networks.md
content/tcf/bc-ministry-of-health.md
content/tcf/bc-public-service.md
content/tcf/bci.md
content/tcf/centre-for-digital-media.md
content/tcf/fortinet.md
content/tcf/hp.md
content/tcf/icbc.md
content/tcf/lmi-technologies.md
content/tcf/olympic-industries.md
content/tcf/orbis.md
content/tcf/procurify.md
content/tcf/reliable-controls.md
content/tcf/safe-software.md
content/tcf/skybox-labs.md
content/tcf/teck.md
content/tcf/vizzion.md
themes/hugo-bootstrap-5/layouts/tcf/tcf-companies.html
themes/hugo-bootstrap-5/layouts/tcf/tcf-company.html
themes/hugo-bootstrap-5/layouts/tcf/tcf-main.html

This PR redesigns the company cards for the TCF page as per [this discussion](https://ubccsss.slack.com/archives/C03G2GP5UUX/p1672364378505579).

Redesign TCF page company cards

---

content/services/tutor.md
data/tutor.yaml
themes/hugo-bootstrap-5/layouts/tcf/tcf-day-of.html

This PR [removes a tutor as per request and adds tutoring removal instructions](https://ubccsss.slack.com/archives/C03G2GP5UUX/p1675019512353109).

Remove tutor + add tutoring removal instructions

---

themes/hugo-bootstrap-5/layouts/partials/course/grades.html
themes/hugo-bootstrap-5/layouts/partials/github-pr-form.html
themes/hugo-bootstrap-5/layouts/services/course.html

This PR moves the course reviews form to the top of the course reviews page as per suggestion by Shubh. Let me know what y'all think and if this positioning looks alright!

Move course reviews form to top

---

themes/hugo-bootstrap-5/layouts/partials/github-pr-form.html
themes/hugo-bootstrap-5/layouts/services/course.html

This PR fixes the course reviews issue #398.

Fix course reviews div

---

content/cube-talks/ep-1-scarlet-nguyen.md
themes/hugo-bootstrap-5/layouts/cube-talks/cube-talks-episode.html

Add speakers to podcast site

---

content/events/2023-03-06-csss-x-leetcode-legends-workshops.md
static/files/leetcode-legends.ics

Change Leetcode Legends link

---

data/tutor.yaml

Remove tutor

---

data/tutor.yaml

Remove Jay Ho

---

content/_index.md
content/events/2023-03-06-csss-x-leetcode-legends-workshops.md
layouts/index.html
static/files/leetcode-legends.ics

This PR:
- removes course review box from landing page
- adds Instagram to the main CTA
- adds end date to the Leetcode Legends workshops

Misc. polishes

---

content/cube/location.md

Replace old link with Google Maps:
Before:
After:

Fix Map Embedding

---

content/services/courses/cpsc-402.md
content/services/courses/cpsc-417.md
content/services/courses/cpsc-424.md
content/services/courses/cpsc-426.md
content/services/courses/cpsc-427.md
content/services/courses/cpsc-445.md
content/services/courses/cpsc-447.md
content/services/courses/cpsc-490.md
content/services/courses/cpsc-501.md
content/services/courses/cpsc-507.md
content/services/courses/cpsc-522.md
content/services/courses/cpsc-524.md
content/services/courses/cpsc-547.md
content/services/courses/cpsc-550.md

Update Course Reviews DB according to UBC's official CPSC course offerings for 2023-2024.
Before:
After:

Update Course Offerings for Course Reviews DB

---

data/tutor.yaml

This PR adds 6 new tutors to the website
Also now fixes #478

update tutor list

---

static/_redirects

redirect to qualtrics form for the workshop next week

add /intern redirect

---

content/cube/menu.md

Someone came to the cube and noted that the price on the website is different from the actually price of products. So I updated a few items in Food Price List. I didn't do an in depth update because our new system is under development. So I just updated some of the prices.

Update Food Price List

---

content/posts/2007-03-13-attend-the-northwestern-technology-conference-for-undergraduates!.md

There is a small spelling mistake in an old post. 
"calender" --> "calendar"
It's not a big deal, but I fixed it anyways.

Fixed spelling mistake

---

static/files/tcf2024/TCF-2024-Registration-Package.pdf

tcf package fix coloring

---

data/courseReviews/cpsc-310.yaml

Reverts ubccsss/ubccsss.org#554, will reach out to the author of the PR to request edits as per our policy on constructive criticism.

Revert "New review for CPSC 310 by quartz imaging is a gift that keeps on giving"

---

data/courseReviews/cpsc-310.yaml

Reverts ubccsss/ubccsss.org#562, as author of the original review has edited their review to comply with our policies.

Revert "Revert "New review for CPSC 310 by quartz imaging is a gift that keeps on giving""

---

LICENSE
config/_default/config.yml

Update year to 2024

---

themes/hugo-bootstrap-5/layouts/tcf/tcf-main.html

As per [here](https://discord.com/channels/1103428719147745341/1163212522355183766/1194167476683030598).
@wgervasio - could you double check the wording? Feel free to merge on approval.

[TCF] Add student reg. disclaimer

---

content/about/partners.md

added sponsorship cta button

---

data/tutor.yaml

Per tutor's request (#627):
- Removed rates
- Updated availablility
- Updated bio description

Update tutor info

---

data/tutor.yaml

Updated tutor list.
Issue: #650

feat: remove Dane from tutor list

---

data/tutor.yaml

Updated tutor.yaml
Issue: #652

feat: update david tutor details

---

data/tutor.yaml

feat: added Mourud as tutor

---

data/tutor.yaml

Changing the current Rate (Phuong Nguyen)

---

data/tutor.yaml

feat: updated tutor details

---

themes/hugo-bootstrap-5/layouts/tcf/tcf-main.html

**Added the Event Package to the TCF Page** 
Before: 
After: 
**Added WiCS and WiDS in TCF partners** 
Before: 
After:

TCF Update on adding partners and event package

---

themes/hugo-bootstrap-5/layouts/tcf/tcf-main.html

Added the registration link for TCF 2025

---

data/tutor.yaml

Changed the rate from $40-60 to $60-80

Changed the hourly rate for a tutor

---

static/_redirects

Will be merged when elections start.

Added qualtrics form for 2025 elections

---

data/tutor.yaml

Updated the tutor description and courses:

Changed description for tutor (Alisa Dulalia)
