content/about/_index.md
Improve awkward flow, grammatical issues, paragraph development, coherence, verb strength, accuracy of information. Remove dangling modifiers and redundant ideas, as well as semicolon abuse and other punctuation mishaps. Smooth tone and add small rhetorical flair. 
Assumed we cannot modify mission statement.
Reviewer: @ubccsss/vp-communications
Thanks!
=> Suggest copywriting changes

assets/css/styles.css
This PR fixes #78, in which we noticed that the top navbar was still slanted on mobile, as well as not opening on mobile.
The cause of this issue was the collapse plugin, which used different attributes on Bootstrap 5.0 compared to the version the theme was currently built against. This PR replaces the `data-toggle` / `data-target` with their Bootstrap 5.0 versions.
This PR also un-slants the top navbar on mobile. Keeping it slanted would have also slanted the text in the navbar pulldown. As well, the top slant wasn't significant enough on mobile, and might have seemed like a weird bug, so the page now has the navbar fully horizontal on mobile and slanted on desktop.
=> Fix mobile nav not opening

config.yml
This PR updates the copyright year range as per #72.
=> Update copyright to include 2021

content/cube/menu.md
This PR fixes the last bullet in #72, removing the old references to [https://ubccsss.org/club/prices](https://ubccsss.org/club/prices).
- Also removed the alias (so that people aren't confused with both links).
=> Remove alias and update link

data/tutor.yaml, i18n/en.yaml, layouts/shortcodes/tutors.html
This PR adds filtering by course to the [tutors](https://ubccsss.org/services/tutor/) page (#12, and our conversation on Zoom):
- Restructured the `data/tutor.yaml` to use a YAML list of course strings (with the slight side effect that courses are now 'AAAABBB' codes instead of 'AAAA BBB'
- Built dropdown from list of unique courses over all tutors - this will update by itself on build if we add new tutors in the future
- Added a bit of JS to toggle visibility of cards based on their course codes, which are stored as classes (why I needed the course codes to be all one word)
=> Add filtering for tutoring page

archetypes/posts.md, content/posts/2022-01-11-recap-2021.md, layouts/posts/content.html
This PR adds post template overrides, so that the rendering of posts are exactly the same as events (#124):
- Adds an `archetypes/posts.md` so that whenever `hugo new posts/20XX-XX-XX-XXXX.md` is run, a template is auto-filled. This template was largely copied from the `events` template, and contains fields for author, tags, and categories. Previously, these fields weren't present, and needed to be manually edited.
- Adds a `layouts/posts/content.html` for the summaries that we use on the main homepage. This is also largely copied from the `events` template. The main difference here from the previous behaviour is a linebreak and some additional attribution information.
(This PR also touches the 2021 recap post to remove the unnecessary linebreak - the layouts should handle that now!)
=> Add post template overrides

assets/js/grades-api.js, layouts/partials/course/grades.html
I updated the API endpoint to work with the new version. 
new endpoint example: [https://ubcgrades.com/api/v2/course-statistics/UBCV/CPSC/221](https://ubcgrades.com/api/v2/course-statistics/UBCV/CPSC/221)
It doesn't work locally due to CORS, but it should work on the live version (maybe).
close #109
=> Updated ubcgrades API endpoint

layouts/partials/search-box.html
This PR fixes some mobile-specific display issues (#149):
- Google Programmable Search seems to use `mobile+en.css` styles when it detects certain user agents (maybe why this didn't come up in testing)
- The issues Asad brought up seem to be a problem with Google's CSS somewhere, so I applied override styles to what I *think* that it was supposed to look like
- I applied this to all viewports <768px wide, so that we have consistent display when on a smaller Chrome or desktop window, and also when on an actual mobile device. The mobile display style now no longer depends on Google's mobile CSS.
I tested this just with my iPhone so this might not work entirely on Android - please let me know if there are any fixes to be made or anything I missed!
=> Add mobile styling fixes for Programmable Search

assets/css/styles.css, layouts/partials/search-box.html
Fixed background color (#FFF to #FCFCFC) and extended search bar to full width for smaller devices.
Before:
After:
=> Fixed css for search bar

data/social.yml, static/modules/linktree.svg
This PR adds the Linktree to the top of the elsewhere section in the sidebar as discussed on Slack.
=> Add Linktree

assets/js/newsletter.js
Currently, the newsletter signup modal will continue to spawn the darkened background at an interval of 10 seconds. If a user navigates to our page for the first time, navigates off the page for a couple minutes, then comes back and clicks on one of the buttons, the backgrounds won't disappear, so they'll see a completely dark page.
Should be fixed with `setTimeout`, which runs only once.
=> Fix setInterval → setTimeout

assets/js/create-github-issue.js, themes/hugo-bootstrap-5/layouts/partials/course/review.html, themes/hugo-bootstrap-5/layouts/partials/github-issue-form.html
This PR:
- [renames the reference field to attribution, and makes the field optional](https://ubccsss.slack.com/archives/C03G2GP5UUX/p1665858390287769)
- [adds a semester taken input to the course review form](https://ubccsss.slack.com/archives/C03G2GP5UUX/p1665858431366749)
- adds the parameter to the GitHub issue creation script
No current reviews have this yet, but the session taken information would look like:
=> Add course session taken information

content/about/clubs.md, themes/hugo-bootstrap-5/layouts/shortcodes/club-calendar.html
This PR is part of #255 - it adds an events calendar similar to the one on our homepage, but can include multiple event feeds. The shortcode takes in any number of hosted ICS files (calendar event format files that can be exposed through GCal), and displays them on the clubs page.  
Currently, only the CSSS events are shown, but other feeds can easily be added pending more outreach for club events! 
Let me know if an exec's email should be listed instead of redirecting to the suggestions box.
=> Add shortcode for clubs unified calendar

config/_default/menu.yml, layouts/partials/header.html
This PR removes the databases dropdown in favour of having the exams + course reviews in the actual header [as per here](https://ubccsss.slack.com/archives/C03G2GP5UUX/p1666056465463029).
=> Move exams + course reviews out of header

assets/js/create-github-pr.js, themes/hugo-bootstrap-5/layouts/partials/course/grades.html, themes/hugo-bootstrap-5/layouts/partials/course/review.html, themes/hugo-bootstrap-5/layouts/partials/github-pr-form.html, themes/hugo-bootstrap-5/layouts/services/course.html
This PR:
- closes #313 by adding a button below the average course grade and description to link to the review form
- closes #307 
- closes #306 by adding 'Course description', and also more spacing around the `<hr>`s as mentioned
- closes #300 
- adds a loading spinner to the submission button since creating a PR takes a bit longer than creating an issue, and it can be a bit confusing for users if their form appears not to have submitted and there's no visual feedback besides disabling the button.
=> Various course review polishes

docs/clubs-ics-events.md, layouts/index.html, themes/hugo-bootstrap-5/layouts/shortcodes/calendar.html, themes/hugo-bootstrap-5/layouts/shortcodes/club-calendar.html
This PR closes #325.
Previously, [open-web-calendar](https://github.com/niccokunzmann/open-web-calendar) was hosted on Heroku. However, Heroku's free tier has shut down, and Asad noticed that our calendar wasn't working.
This PR just ports to their new hosting address - additional diffs are just from formatting.
=> Fix calendar hosting

themes/hugo-bootstrap-5/layouts/partials/course/rating.html, themes/hugo-bootstrap-5/layouts/partials/course/review.html
For some reason, the website is missing spacing despite it being present on the preview and localhost. I think something like this happened before with something else. This should fix it, I think.
This fix adds spacing in-between svgs below:
=> hotfix: spacing for circles

.github/workflows/main.yml, .prettierrc
The correct option is `useTabs` and we are using the default value.
=> Removed non-existent `tabs` option and updated actions/checkout to v3

.github/workflows/main.yml
This PR addresses #356.
Our previous workflow ran on PR updates to format code and push formatted commits to the PR branch. This had two issues (that we couldn't notice until it was deployed, and were low severity, so no worries!):
- The action couldn't pull branches on forks (can be fixed with `repository: ${{ github.event.pull_request.head.repo.full_name }}`, but see next point)
- The action doesn't have permission to push updates to PR branches unless the PR author expressly authorizes the action to collaborate on their forked repo
This new GitHub workflow formats files only after commits have been made to `main`. It would have been cleaner to do this in the PR, but it seems like with our current workflow the easiest path forward is to run it on push to main instead.
An alternative …
=> Run Prettier on push to main instead of per-PR

themes/hugo-bootstrap-5/layouts/tcf/tcf-day-of.html, themes/hugo-bootstrap-5/layouts/tcf/tcf-main.html
This PR fixes the issue of the TCF company preview grid not fully filling:
This was due to iterating through all pages in `content/tcf/` instead of all TCF company pages in `content/tcf`.
=> Fix TCF page companies display

content/about/team/officers/2021.md
This PR fixes the 2021-2022 communications officers list [as per Slack](https://ubccsss.slack.com/archives/C03G2GP5UUX/p1675395100381619?thread_ts=1675361578.994939&cid=C03G2GP5UUX).
=> Fix 2021 Officers List

data/tutor.yaml, themes/hugo-bootstrap-5/layouts/shortcodes/tutors.html
This PR closes #376. This PR also fixes an issue with tutoring sorting due to several recent tutor YAMLs having spaces in their course code names. I've left a comment to avoid this in the future.
=> Update tutors + fix tutor sorting

content/events/2023-01-19-technical-career-fair.md
This PR closes #383.
The `/events` page loads the HTML of each event, and in the TCF HTML I'd added a simple `window.location.href` redirect to the TCF site.
I've added a guard now so it'll only redirect when you go to the event page, and added a link for people to click if they find the TCF post via the `/events` page.
=> Add TCF page pathname guard

assets/js/create-github-pr.js, content/about/team/officers/2021.md, content/events/2023-02-06-computer-science-hoodies.md, content/events/2023-02-14-valentines-day-bubble-tea-event.md, content/services/courses/_index.md, data/courseReviews/cpsc-304.yaml, data/courseReviews/cpsc-310.yaml, data/courseReviews/cpsc-312.yaml, data/courseReviews/cpsc-317.yaml, data/courseReviews/cpsc-320.yaml, data/courseReviews/cpsc-404.yaml, data/tutor.yaml, layouts/partials/header.html, themes/hugo-bootstrap-5/layouts/partials/github-pr-form.html, themes/hugo-bootstrap-5/layouts/tcf2023/tcf-main.html
This PR adds the email field for the hoodie / AMS gift card raffle on the course reviews page.
The main course reviews page now has a small card explaining the raffle, the course review form also has this information, and the hoodies post also has a small blurb added.
=> Add raffle to course reviews page

.prettierignore, themes/hugo-bootstrap-5/layouts/partials/course/review.html
This PR fixes the course review date spacing. Currently, it looks like this because Prettier autoformatted in newlines, adding indenting whitespace:
I've added a `.prettierignore` file to prevent it from being autoformatted again in the future (we can manually run Prettier locally and check for formatting issues first before committing). We should also be careful about autoformatting in PRs going forwards!
=> Fix course review date spacing

content/events/2023-03-06-csss-x-leetcode-legends-workshops.md, static/files/leetcode-legends.ics, themes/hugo-bootstrap-5/layouts/events/list.ics, themes/hugo-bootstrap-5/layouts/events/single.html, themes/hugo-bootstrap-5/layouts/events/single.ics, themes/hugo-bootstrap-5/layouts/partials/event/when.html
This PR updates the Leetcode Legends workshop blurbs and adds the ability for custom ICS events to be specified and added to the calendar.
To add a custom ICS file (to take advantage of more complex recurrence behaviour), export an ICS file from Google Calendar or something similar, strip everything besides the `VEVENT` blocks, and add its file path, with `static`, in the `file_ics` field.
Also, the `when` field will now override the `When:` display at the bottom of each event.
This will not update in the deploy preview as we're linking to the hosted `ubccsss.org` ICS file, so please review locally.
=> Add Leetcode Legends event updates

assets/js/create-github-pr.js, content/services/courses/_index.md, themes/hugo-bootstrap-5/layouts/partials/github-pr-form.html
This PR removes the raffle copy from the `/services/courses` page and the 'add new review' form.
I've left the email functionality in the Worker for now. We can reuse it if we plan to run something like this again in coming terms.
Will self-approve this PR.
=> Remove Course Reviews raffle copy

content/about/clubs.md
This PR removes Bizhacks from the `/about/clubs` page as they're no longer operating.
=> Remove Bizhacks from clubs page

content/about/team/officers/2021.md
Small bug but I thought maybe we can keep the [officer titles](https://ubccsss.org/about/team/officers/) in order so we have:
```
Current Officers—2023–2024 
Officers—2022–2023 
Officers—2021–2022 
Officers—2018–2019
``` 
Currently, we have:
=> Re-order title

content/services/tutor.md
This PR replaces the tutoring forms link [here](https://ubccsss.org/services/tutor/) with a new Google Form with a webhook trigger attached.
For future documentation, the associated Google Apps script is in the `Website` folder of the `CSSS 2023-2024` folder, and the VP Academic Gmail account owns the Google Form and responses sheet.
=> Replace tutoring form link

README.md
I updated the bash commands in the installation documentation in the root README.md file. I changed "nvm use" to "nvm update". The command "nvm use" only works if the correct node version is already installed. The command "nvm install" does the same thing, but also installs the correct node version if it isn't already installed.
=> Update Installation Documentation

themes/hugo-bootstrap-5/layouts/tcf/tcf-main.html
This PR makes each partner card take up the same height, as well as making the cards more mobile-friendly.
=> Fix TCF partner card visual bugs

content/posts/2019-01-19-career-opportunitiees.md, themes/hugo-bootstrap-5/theme.toml
Using the new and improved [link-inspector](https://github.com/justindhillon/link-inspector), I found some new broken links. I decided not to fix the links in the _very_ old posts because there won't be much benefit. If you find this pr useful, give [link-inspector](https://github.com/justindhillon/link-inspector) a star :star: 
https://github.com/NotWoods/hugo-bootstrap-5/blob/master/LICENSE.md --> https://github.com/NotWoods/hugo-bootstrap-5/blob/main/LICENSE.md
https://www.battlesnake.io/ --> https://play.battlesnake.com/
https://www.battlesnake.io/resources/ --> https://docs.battlesnake.com/
=> More Broken Links

themes/hugo-bootstrap-5/layouts/tcf2023/tcf-companies.html, themes/hugo-bootstrap-5/layouts/tcf2023/tcf-company.html, themes/hugo-bootstrap-5/layouts/tcf2023/tcf-day-of.html, themes/hugo-bootstrap-5/layouts/tcf2023/tcf-main.html
This PR adds (as per Alice):
- `[Past Event]` to the title of each of the 2023 TCF pages
- a 'looking for TCF 2024?' link to each of the old pages:
Let me know if you have anywhere else you'd like to add a note!
=> [TCF] Add past event notes on 2023 pages

content/services/_index.md, content/services/exams/_index.md, content/services/exams/cpsc101.md, content/services/exams/cpsc110.md, content/services/exams/cpsc121.md, content/services/exams/cpsc173.md, content/services/exams/cpsc210.md, content/services/exams/cpsc211.md, content/services/exams/cpsc213.md, content/services/exams/cpsc221.md, content/services/exams/cpsc302.md, content/services/exams/cpsc311.md, content/services/exams/cpsc312.md, content/services/exams/cpsc313.md, content/services/exams/cpsc314.md, content/services/exams/cpsc320.md, content/services/exams/cpsc322.md, content/services/exams/cpsc340.md, content/services/exams/cpsc404.md, content/services/exams/cpsc422.md, content/services/exams/cpsc448b.md, content/services/exams/uncategorized.md, data/exams/cpsc320.yaml, layouts/index.html, themes/hugo-bootstrap-5/layouts/shortcodes/exams-hint.html
This PR adds:
- an `exams-hint` shortcode that pulls from `data/exams/<course>.yaml` to render hints (easiest way to add hints without massively restructuring existing exam pages)
- an additional 'resources' section to some courses
- additional past exams that I scrounged around to find
...and renames the Exams DB to the Study Stack.
Keeping as a draft PR before I bring it up with exec team / academic team!
=> [Study Stack] Revamp!

package.json
I added ```"private": true``` to package.json. This prevents someone from accidentally publishing the website to the npm repositories. This is standard practice for websites that use npm.
Documentation: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#private
=> Something about package.json

content/about/_index.md, content/about/code-of-conduct.md, data/footer.yaml
This pull request adds the Code of Conduct to the About page and includes a link to it in the footer
=> Added Code of Conduct 

layouts/partials/header.html, layouts/partials/sidebar.html
- Updated <img> tags in the social media section to include the 'icon-image' class.
- Enables JavaScript control over icon colors based on dark mode toggle.
- Added a 100ms delay to allow DarkReader to fully apply its styles
before updating social icon colors.
=> feat: Add 'icon-image' class to social icons for dark mode styling

content/events/2024-10-18-hacktoberfest-git-workshop.md, layouts/index.html, layouts/partials/display-events.html, layouts/partials/event-carousel.html, themes/hugo-bootstrap-5/layouts/_default/card.html
Added a carousel for events on the landing page with tabs: upcoming and past.
**Notes:**
- Carousels will show the 28 most recent events in total.
- On page load, the upcoming events tab will be selected by default. If there are no upcoming events, the past events carousel will be selected instead.
- All events filtering is on a day basis; time is not considered. This means:
- Events starting and ending on the same day are moved to the past events carousel a day after the event start date. E.g an event occurring Nov 4th will remain in the upcoming events carousel for the whole day, even if the event finished earlier that day.
- If an event spans multiple days, the event will remain in upcoming events until it concludes.
- An event is highlighted if it's occurring within the next 7 days …
=> Landing page event carousels
